#!/bin/bash

root=$(git rev-parse --show-toplevel)
compose_file="${root}/docker-compose.yml"

while true
do
        docker compose logs -f ${compose_file} --follow -t
        echo "Detached from logs. Re-attaching in 5 seconds..."
        echo "Press Ctrl+C to cancel."
        sleep 5
done
